More Scraper Improvements
umdio/umdio pull request #208
Opened 2021-04-24 02:27 UTC by DonIsaac

Requires #194 to be merged first

- chore: added `dev:db` command to connect to DB with psql shell
- fix(scrapers/sections): Fixed bug causing abnormally long scrape times
- up(scrapers): Finished converting the rest of the scrapers into
   classes
- up(scrapers): Added progress bars to all scrapers

2021-04-25 20:50 UTC, DonIsaac commented
This PR is ready for review 👍

2021-04-27 01:12 UTC, McIntireEvan commented
I skimmed it and it seems pretty good. One thing before I approve - can you post sample output, with the progress bar? I'm worried about how it will interact with the logger, and how readable logs will remain after it, e.g. looking back at a scrape that auto-ran. (I can also run it on my machine later, but it helps completeness of the PR to have it explicitly here as well)

2021-04-27 02:36 UTC, DonIsaac commented
@McIntireEvan they look kind of like this
![image](https://user-images.githubusercontent.com/22823424/116176195-b89ac280-a6df-11eb-8ae7-7f10d47da94d.png)

the `log` command that I "wrote" is taken from `ruby-progressbar`'s `#log` function. However, their `log` function is equivalent to `puts`, so for those sweet, sweet timestamps I re-used the clear/refresh logic they used

2021-05-02 02:54 UTC, tybug requested changes

2021-05-02 02:54 UTC, tybug commented on app/scrapers/courses_scraper.rb
> +      # logger.debug(prog_name) { "fetching #{url}" }
remove commented code?

2021-05-02 02:54 UTC, tybug commented on app/scrapers/majors_scraper.rb
> +      # logger.debug { "inserting #{major[:name]}" }
same here

2021-05-02 02:54 UTC, tybug commented on app/scrapers/map_scraper.rb
> +  end
why not a static method instead?

2021-05-02 14:56 UTC, DonIsaac commented on app/scrapers/map_scraper.rb
> +  end
Made it easier to refactor ¯\_(ツ)_/¯ the scrapers could use some more cleanup as URL handling isn't super consistent, some things still need to be broken into helper functions, etc. but that's cleanup for another PR IMO.

2021-05-02 21:21 UTC, tybug approved these changes

2021-05-03 13:12 UTC, merged